language: java

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/android-sdk-dl
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.android/build-cache
env:
  - ANDROID_HOME=$HOME/.android

os: linux
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - mkdir -p $HOME/.android
  - mkdir -p $ANDROID_HOME/licenses
  - mkdir -p $HOME/safeNetFiles
  - wget -O $HOME/safeNetFiles/log.toml https://raw.githubusercontent.com/maidsafe/safe_app_csharp/master/SafeApp.Tests/log.toml
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
install:
  - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl --create-dirs https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -o $HOME/android-sdk-dl/sdk-tools.zip ; fi
  - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $ANDROID_HOME
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools' > /dev/null
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools' > /dev/null
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'emulator' > /dev/null
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-26' > /dev/null
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'system-images;android-24;default;armeabi-v7a' > /dev/null
before_script:
  - echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test  -k 'system-images;android-24;default;armeabi-v7a' > /dev/null
  - curl https://gist.githubusercontent.com/lionel1704/c696119831cfda3b2c63ce8916ba21ef/raw/7c60e9e10e8abcb275361685d721be986d1be3e6/android-wait-for-emulator > android-wait-for-emulator
  - $ANDROID_HOME/tools/emulator -avd test -no-window -no-audio &
  - chmod +x ./android-wait-for-emulator
  - ./android-wait-for-emulator
  - $ANDROID_HOME/platform-tools/adb shell input keyevent 82 &
script:
  - chmod +x gradlew
  - ./gradlew check
  - $ANDROID_HOME/platform-tools/adb push $HOME/safeNetFiles/log.toml /data/user/0/net.maidsafe.sample.test/files
  - ./gradlew connectedMockDebugAndroidTest --info
  - echo travis:$SSHPWD | sudo chpasswd
  - sudo sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' /etc/ssh/sshd_config
  - sudo service ssh restart
  - sudo apt-get install sshpass
  - sshpass -p $SSHPWD ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no maidsafe@$SSHIP -p 52436
after_script:
  - $ANDROID_HOME/platform-tools/adb pull /data/user/0/net.maidsafe.sample.test/files $HOME/safeNetFiles/Client.log
  - cat $HOME/safeNetFiles/Client.log
